name: release-to-github
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be created'
        required: true
        default: 'v1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}


      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          base-ref: ${{ github.event.inputs.tag }}

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        id: release
        with:
          version: ${{ github.event.inputs.tag }}
          release: true
          body: ${{ steps.changelog.outputs.changelog }}

      - name: Release Upload Assets
        uses: jaywcjlove/github-action-upload-assets@main
        continue-on-error: true
        with:
          tag: ${{ github.event.inputs.tag }}
          asset-path: target/*.jar