name: release-to-github
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be created'
        required: true
        default: 'v1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - run: echo "previous_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo '')" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        if: env.previous_tag
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          filter-author: (jaywcjlove|小弟调调™|dependabot|renovate\\[bot\\]|dependabot\\[bot\\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        id: release
        if: steps.create_tag.outputs.successful == 'true'
        with:
          version: ${{steps.create_tag.outputs.version}}
          release: true
          body: ${{ steps.changelog.outputs.changelog }}

      - name: Release Upload Assets
        uses: jaywcjlove/github-action-upload-assets@main
        continue-on-error: true
        with:
          tag: ${{ steps.release.outputs.version }}
          asset-path: target/*.jar