name: release-to-github
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be created'
        required: true
        default: 'v1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package

      - name: Create Tag
        id: create_tag
        run: |
          git tag ${{ github.event.inputs.tag }}
          git push origin ${{ github.event.inputs.tag }}

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.PERSONAL_TOKEN }}
          base-ref: ${{ github.event.inputs.tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: target/*.jar