name: release-to-github
on:
  workflow_dispatch:
    inputs:
      releaseversion:
        description: 'Release version'
        required: true
        default: '1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn clean package
      - name: Create tag if it does not exist
        run: |
          git fetch --tags
          if git rev-parse "$GITHUB_REF" >/dev/null 2>&1; then
            echo "Tag ${{ github.event.inputs.releaseversion }} already exists."
          else
            echo "Tag ${{ github.event.inputs.releaseversion }} does not exist. Creating it now..."
            git tag ${{ github.event.inputs.releaseversion }}
            git push origin ${{ github.event.inputs.releaseversion }}
          fi
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.PERSONAL_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag: ${{ github.event.inputs.releaseversion }}
          name: ${{ github.event.inputs.releaseversion }}
          tag_name: ${{ github.event.inputs.releaseversion }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: target/*.jar